[versions]
circe = "0.14.15"
junitPlatform = "1.13.1"
pekko = "1.2.1"
pekkoHttp = "1.3.0"
promVer = "0.16.0"
pureconfig = "0.17.9"
sttp = "4.0.13"
testcontainers = "1.20.4"

[libraries]

circe-core = { module = "io.circe:circe-core_3", version.ref = "circe" }
circe-generic = { module = "io.circe:circe-generic_3", version.ref = "circe" }
circe-parser = { module = "io.circe:circe-parser_3", version.ref = "circe" }


junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junitPlatform" }
junit-platform-engine = { module = "org.junit.platform:junit-platform-engine", version.ref = "junitPlatform" }
junit-scala-test-plus = { module = "org.scalatestplus:junit-5-13_3", version = "3.2.19.0" }

logback = 'ch.qos.logback:logback-classic:1.5.20'

pekko-actor = { module = 'org.apache.pekko:pekko-actor-typed_3', version.ref = "pekko" }
pekko-circe = "com.github.pjfanning:pekko-http-circe_3:3.6.0"
pekko-http = { module = 'org.apache.pekko:pekko-http_3', version.ref = "pekkoHttp" }
pekko-http-testkit = { module = "org.apache.pekko:pekko-http-testkit_3", version.ref = "pekkoHttp" }
pekko-kafka = "org.apache.pekko:pekko-connectors-kafka_3:1.1.0"
pekko-http-backend = { module = "com.softwaremill.sttp.client4:pekko-http-backend_3", version.ref = "sttp" }
pekko-testkit = { module = "org.apache.pekko:pekko-actor-testkit-typed_3", version.ref = "pekko" }
pekko-stream = { module = 'org.apache.pekko:pekko-stream_3', version.ref = "pekko" }
pekko-stream-testkit = { module = "org.apache.pekko:pekko-stream-testkit_3", version.ref = "pekko" }

prometheus-client = { module = "io.prometheus:simpleclient", version.ref = "promVer" }
prometheus-client-common = { module = "io.prometheus:simpleclient_common", version.ref = "promVer" }
prometheus-client-hotspot = { module = "io.prometheus:simpleclient_hotspot", version.ref = "promVer" }


puml = "net.sourceforge.plantuml:plantuml:1.2024.7"

pureconfig-core = { module = "com.github.pureconfig:pureconfig-core_3", version.ref = "pureconfig" }
pureconfig-generic-scala3 = { module = "com.github.pureconfig:pureconfig-generic-scala3_3", version.ref = "pureconfig" }

scala = "org.scala-lang:scala-library:3.3.4"
scala-test = "org.scalatest:scalatest_3:3.2.19"

sttp-circe = { module = 'com.softwaremill.sttp.client4:circe_3', version.ref = "sttp" }
sttp-core = { module = 'com.softwaremill.sttp.client4:core_3', version.ref = "sttp" }
sttp-pekko-backend = { module = 'com.softwaremill.sttp.client4:pekko-http-backend_3', version.ref = "sttp" }

testcontainers-core = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-kafka = { module = "org.testcontainers:kafka", version.ref = "testcontainers" }

[bundles]
circe = [
    "circe-core", "circe-generic", "circe-parser"
]
prometheus = [
    "prometheus-client", "prometheus-client-common", "prometheus-client-hotspot"
]

[plugins]
